### ISSUE TITLE
Allow medical assistants to register new patients 

### ISSUE THREAD

**Issue by fdiazmlg** [JoseMariaAlvarez/ISA2017#2]

**Comment by ineedblood** [comment]
#2 closed.

Working as intended

https://github.com/JoseMariaAlvarez/ISA2017/commit/6d346264dd046f57aee39ffd993e237124345cdc

**Comment by fdiazmlg** [comment]
Working as intended

https://github.com/JoseMariaAlvarez/ISA2017/commit/6d346264dd046f57aee39ffd993e237124345cdc
